version: '3.8'
services:
  node:
    image: mcr.microsoft.com/playwright:v1.46.0-jammy
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./:/app/
    tty: true
    stdin_open: true
    command: ["npm", "run", "dev"]
